#!/usr/bin/python3

from database import Location, Event, engine
from sqlalchemy import sql
from datetime import datetime

conn = engine.connect()

print("CUGOSOC Location Add")
print()
query = sql.select([Location.id, Location.name, Location.address]);
res = conn.execute(query)
for row in res.fetchall():
    print("[" + str(row.id) + "] " + row.name + " (" + row.address + ")")
print()
print("WARNING - before continuing, please check the location is not listed above")
print()
name = str(input("Enter location name: "))
address = str(input("Enter location address: "))
print()
print(name)
print(address)
print()
correct = input("Is the above correct? [y/N]: ")

if correct == 'Y' or correct == 'y':
    print("Adding location...")
    query = sql.insert(Location.__table__,
            values={
                Location.name: name,
                Location.address: address,
            }
    )
    conn.execute(query)
    print("Added!")
else:
    print("Aborting")
