#!/usr/bin/python3

from database import Location, Event, engine
from sqlalchemy import sql
from datetime import datetime

conn = engine.connect()

print("CUGOSOC Event Add")
name = str(input("Enter event name: "))
print()

locations = []
query = sql.select([Location.id, Location.name, Location.address]);
res = conn.execute(query)
for row in res.fetchall():
    print("[" + str(row.id) + "] " + row.name + " (" + row.address + ")")
    locations.append(row.id)
print()

location = int(input("Enter event location (index from above): "))
if location not in locations:
    raise ValueError("Location must point to a location in the database")
date = datetime.strptime(input("Input event date (dd/mm/yyyy): "), "%d/%m/%Y").date()
start = datetime.strptime(input("Input event start time (HH:MM): "), "%H:%M").time()
end = datetime.strptime(input("Input event end time (HH:MM): "), "%H:%M").time()
description = str(input("If the event has a description, enter its relative path: "))
facebook_link = str(input("If the event is listed on Facebook, enter the Facebook URL: "))
tournament = input("Enter if the event is a tournament [y/N]: ")
tournament = (tournament == 'y' or tournament == 'Y')

print()
print(name)
print(location)
print(date)
print(start)
print(end)
print(description)
print(facebook_link)
if tournament:
    print("Tournament")
else:
    print("Not a tournament")
print()
correct = input("Is the above correct? [y/N]: ")

if correct == 'Y' or correct == 'y':
    print("Adding event...")
    query = sql.insert(Event.__table__,
            values={
                Event.name: name,
                Event.location: location,
                Event.date: date,
                Event.start: start,
                Event.end: end,
                Event.tournament: tournament,
                Event.description: description,
                Event.facebook_link: facebook_link,
            }
    )
    conn.execute(query)
    print("Added!")
else:
    print("Aborting")
